services:
  - docker

env:
  - TEST_GROUP=2-3-7-p2
  - TEST_GROUP=2-latest

before_install:
  - travis_retry wget https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-linux-x86_64
  - sudo mv docker-compose-linux-x86_64 /usr/libexec/docker/cli-plugins/docker-compose
  - sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose
  - docker --version && docker compose version
  - composer self-update --2 && composer self-update --2.2

install:
    - composer install --no-interaction
script:
    - composer run test-static-analysis
    - composer run test:unit
    # Install magento
    - COMPOSER_AFTER_INSTALL_COMMAND='mkdir -p app/etc/ampersand_magento2_log_correlation; cp /current_extension/app/etc/ampersand_magento2_log_correlation/di.xml app/etc/ampersand_magento2_log_correlation/ ;' CURRENT_EXTENSION="." vendor/bin/mtest-make $TEST_GROUP
    # Run integration tests
    - vendor/bin/mtest 'IS_CI_PIPELINE=1 vendor/bin/phpunit -c /var/www/html/dev/tests/integration/phpunit.xml.dist --testsuite Integration --debug'
    # Output the custom loggers command filtering out modules we've accounted for
    - # TODO if [[ $TEST_GROUP = magento_23 ]];     then php bin/magento ampersand:log-correlation-id:list-custom-loggers --filter "Klarna\Core\Logger\Logger" --filter "Dotdigitalgroup\Email\Logger\Logger" --filter "Amazon\Core\Logger\Logger" --filter "Amazon\Core\Logger\IpnLogger" ; fi
    - # TODO if [[ $TEST_GROUP = magento_latest ]]; then php bin/magento ampersand:log-correlation-id:list-custom-loggers --filter "Yotpo\Yotpo\Model\Logger" --filter "Klarna\Core\Logger\Logger" --filter "Dotdigitalgroup\Email\Logger\Logger" --filter "Amazon\Core\Logger\Logger" --filter "Amazon\Core\Logger\IpnLogger" --filter "Magento\AdminAdobeIms\Logger\AdminAdobeImsLogger" ; fi
    # Test di compilation
    - #rm -rf generated
    - #composer install
    - #php bin/magento module:enable --all
    - #php bin/magento setup:di:compile

after_failure:
  - # TODO
  - cd ./vendor/ampersand/travis-vanilla-magento/instances/ampmodule/
  - for r in ./var/report/*; do cat $r; done
  - for l in ./var/log/*;  do cat $l; done
  - ls -l ./dev/tests/integration/tmp/sandbox*/var
  - for r in ./dev/tests/integration/tmp/sandbox*/var/report/*; do cat $r; done
  - for l in ./dev/tests/integration/tmp/sandbox*/var/log/*; do cat $l; done
  - sleep 10;
