name: Integration Test

on:
  push:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - "*.md"
  pull_request:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - "*.md"

jobs:
  compute_matrix:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.supported-version.outputs.matrix }}
      steps:
        - uses: actions/checkout@v2
        - uses: graycoreio/github-actions-magento2/supported-version@main
          id: supported-version
        - run: echo ${{ steps.supported-version.outputs.matrix }}
  integration-workflow:
    needs: compute_matrix
    uses: graycoreio/github-actions-magento2/.github/workflows/integration.yaml@main
    with:
      package_name: ampersand/magento2-log-correlation-id
      matrix: ${{ needs.compute_matrix.outputs.matrix }}
      test_command: ../../../vendor/bin/phpunit ../../../vendor/ampersand/magento2-log-correlation-id/src/Test/Integration
      magento_repository: https://repo-magento-mirror.fooman.co.nz/ 
    secrets:
      composer_auth: '{}'
