name: Unit Test

on:
  push:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - "*.md"
  pull_request:
    branches:
    - main
    paths-ignore:
    - "docs/**"
    - "*.md"

jobs:
  unit-test:
    strategy:
      matrix:
        php_version:
          - 7.4
          - 8.1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: graycoreio/github-actions-magento2/unit-test@main
      with:
        php_version: ${{ matrix.php_version }}
        composer_auth: '{}'
        test_command: composer run test:unit
        magento_repository: https://repo-magento-mirror.fooman.co.nz/ 
